# Generated by Django 5.0.7 on 2024-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.CharField(default='not available', max_length=500),
            preserve_default=False,
        ),
    ]
