# Generated by Django 5.0.7 on 2024-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_remove_blogpost_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content_type',
            new_name='category',
        ),
    ]
