# Generated by Django 5.0.7 on 2024-08-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_content_type_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order', 'blog_post']},
        ),
    ]
